apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - name: api
        image: 10.33.109.104/data-crawling/api:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "64m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000