apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 10.33.109.104/data-crawling/api:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "64m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000