apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapy
  labels:
    app: scrapy
spec:
  selector:
    matchLabels:
      app: scrapy
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: scrapy
    spec:
      containers:
      - name: scrapy
        image: 10.33.109.104/data-crawling/scrapy:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6800